name: Test [General]

on:
  # Run on any push to master and all PRs (any branch)
  push:
    branches: [ master ]
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: pre-commit-
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: pre-commit-pip
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pip freeze --local
      - name: Run pre-commit (push)
        if: github.event_name == 'push'
        run: SKIP=no-commit-to-branch pre-commit run --color=always
      - name: Run pre-commit (PR)
        if: github.event_name == 'pull_request'
        run: |
          git fetch --depth=1 origin ${{ github.base_ref }}
          git diff --name-only origin/${{ github.base_ref }} | xargs pre-commit run --show-diff-on-failure --color=always --files
